Fix wrong plural usage for time in PT-BR
moment/moment pull request #5404
Opened 2020-03-05 15:04 UTC by luizcorreia

This fix #3988

But I need help on 2 test that don't pass, 

Errors:

Module: locale:pt-br Test: date format correctness
Died on test #5     at global.test.QUnit.test (/home/luizcorreia/repos/moment/node_modules/node-qunit/lib/child.js:133:21)
    at defineCommonLocaleTests (/home/luizcorreia/repos/moment/build/umd/test/locale/pt-br.js:141:9)
    at localeModule (/home/luizcorreia/repos/moment/build/umd/test/locale/pt-br.js:286:9)
    at /home/luizcorreia/repos/moment/build/umd/test/locale/pt-br.js:289:5
    at /home/luizcorreia/repos/moment/build/umd/test/locale/pt-br.js:4:43
    at Object.<anonymous> (/home/luizcorreia/repos/moment/build/umd/test/locale/pt-br.js:7:2)
    at Module._compile (internal/modules/cjs/loader.js:955:30): localeData[baseToken].replace is not a function
TypeError: localeData[baseToken].replace is not a function
    at /home/luizcorreia/repos/moment/build/umd/test/locale/pt-br.js:151:56
    at each (/home/luizcorreia/repos/moment/build/umd/test/locale/pt-br.js:12:13)
    at /home/luizcorreia/repos/moment/build/umd/test/locale/pt-br.js:148:17
    at each (/home/luizcorreia/repos/moment/build/umd/test/locale/pt-br.js:12:13)
    at Object.<anonymous> (/home/luizcorreia/repos/moment/build/umd/test/locale/pt-br.js:145:13)

Module: locale:pt-br Test: format
Died on test #18     at global.test.QUnit.test (/home/luizcorreia/repos/moment/node_modules/node-qunit/lib/child.js:133:21)
    at /home/luizcorreia/repos/moment/build/umd/test/locale/pt-br.js:311:5
    at /home/luizcorreia/repos/moment/build/umd/test/locale/pt-br.js:4:43
    at Object.<anonymous> (/home/luizcorreia/repos/moment/build/umd/test/locale/pt-br.js:7:2)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32): Cannot read property 'hours' of undefined
TypeError: Cannot read property 'hours' of undefined
    at LLL (/home/luizcorreia/repos/moment/build/umd/locale/pt-br.js:23:72)
    at Locale.longDateFormat (/home/luizcorreia/repos/moment/build/umd/moment.js:442:48)
    at replaceLongDateFormatTokens (/home/luizcorreia/repos/moment/build/umd/moment.js:624:27)
    at String.replace (<anonymous>)
    at expandFormat (/home/luizcorreia/repos/moment/build/umd/moment.js:629:29)
    at formatMoment (/home/luizcorreia/repos/moment/build/umd/moment.js:614:18)
    at Moment.format (/home/luizcorreia/repos/moment/build/umd/moment.js:3379:22)
    at Object.<anonymous> (/home/luizcorreia/repos/moment/build/umd/test/locale/pt-br.js:340:28)

2020-04-23 14:23 UTC, ichernev commented
@caio-ribeiro-pereira can you comment on this?
@luizcorreia you should only change files under `src/**` not `locale/*` or `package-lock.js`.

2020-04-23 14:27 UTC, caio-ribeiro-pereira reviewed
The translated changes is okay in my opinion

2020-04-28 12:32 UTC, ichernev commented
Note to self: I believe the dynamic long date format tokens are an issue, because they are evaluated once, so whichever format "clicks" the first time, it will be used forever.

2023-12-23 10:50 UTC, ichernev commented
You can try to rebase, and drop the changes outside of `src`.

2023-12-26 22:12 UTC, anandfresh approved these changes

2024-01-03 14:14 UTC, luizcorreia commented
> You can try to rebase, and drop the changes outside of `src`.

Please review now.

2024-07-20 07:31 UTC, anandfresh approved these changes

2026-08-12 05:47 UTC, mattjohnsonpint requested changes
I rebased this to get the tests to run. CI is now failing, and I reproduced the failures locally.

The intended Portuguese grammar change makes sense: use `à` for 00:00 and 01:00, and `às` for 02:00 onward. However, the current implementation causes runtime errors and is not just missing test updates:

- `LLL` and `LLLL` throw because function-valued `longDateFormat` entries do not receive the Moment instance.
- Lowercase `lll` and `llll` also throw because Moment expects the uppercase formats to be strings.
- Capitalizing all month and weekday names is unrelated and breaks existing Portuguese output; please revert those changes.
- The new tests use `hours() > 2`, which is incorrect at exactly 02:00. It should be `hours() >= 2`, or equivalently `hours() < 2` for the singular case.
- The changed files also need to be formatted with Prettier.

Please keep `longDateFormat` values as strings, preserve lowercase month and weekday names, and add deterministic tests covering 00:00, 01:00, 02:00, and a later hour. The calendar functions can select `à` versus `às`, but supporting dynamic `LLL`/`LLLL` would require a broader core change covering formatting, parsing, lowercase formats, and shared locale tests.

2026-08-13 19:09 UTC, mattjohnsonpint approved these changes
Re-reviewed the updated commit. The previous issues are resolved: longDateFormat remains string-valued, locale casing is preserved, calendar output uses à at 00:00/01:00 and às from 02:00 onward, and the tests are deterministic and formatted. I also ran the pt-br locale suite locally (1,104 assertions), ESLint, Prettier, and git diff --check; all passed.

2026-08-13 19:20 UTC, mattjohnsonpint commented
*AI-generated review note.*

I compared this change with CLDR and Brazilian Portuguese references.

CLDR 48 uses a static `às` for Portuguese date/time combinations, including `às 00:00` and `às 01:00`. However, the Brazilian Senate’s communication manual explicitly prescribes `à 0h`, and standard grammar supports singular `à` for the implied `zero/uma hora`, changing to plural `às` from `duas horas` onward. Michaelis also supports the underlying singular/plural agreement.

Therefore, the PR’s rule (`à` at 00:xx and 01:xx; `às` from 02:xx onward) is linguistically sound for formal Brazilian Portuguese, despite intentionally differing from CLDR and some common usage. The retained `HH:mm` notation explains `à 00:00` rather than the Senate’s stylistic `à 0h`.

References:

- https://www12.senado.leg.br/manualdecomunicacao/estilos/hora
- https://michaelis.uol.com.br/moderno-portugues/nocoes-gramaticais/emprego-da-crase/
- https://github.com/unicode-org/cldr-json/blob/main/cldr-json/cldr-dates-full/main/pt/ca-gregorian.json

2026-08-13 19:21 UTC, merged