standalone and format added to "cs" locale
moment/moment pull request #5749
Opened 2020-10-06 12:03 UTC by Kartik18g

I've updated the "cs" locale by implementing standalone and formats, I was confused why these changes were needed because cs locale code was able to handle inflections like `leden - ledna`. `únor - února` `březen-března` etc without any problems. Then I realized adding format and standalone to 'cs' locale makes the code consistent with other locales like 'hi' and 'ru' .
After making changes to the "cs" locale it's test needed to be updated because of moment expecting standalone values, I also added 'format month case test' for accusations and nominations.

Now, for the most part, cs locale code is consistent with other locales, but if you feel something needs to be changed I can do that.

2020-10-07 12:05 UTC, marwahaha commented
@petrbela could you take a look?

2020-10-08 16:03 UTC, petrbela requested changes
The implementation looks good, just added the correct Czech inflections in the comments

2020-10-08 16:03 UTC, petrbela commented on src/test/locale/cs.js
> +            nominative: 'ledna_února_března_dubna_května_června_července_srpena_září_říjena_listopada_prosince'.split(
```suggestion
            nominative: 'ledna_února_března_dubna_května_června_července_srpna_září_října_listopadu_prosince'.split(
```

2020-10-09 04:20 UTC, Kartik18g commented
@petrbela Thanks for providing correct inflections, i've updated them in the latest commit. All tests passed successfully everything looks good, ready to be merged .

2020-10-21 13:06 UTC, Kartik18g commented
@petrbela  can you take a look at it?

2020-10-21 13:15 UTC, petrbela requested changes

2020-10-21 13:15 UTC, petrbela commented on src/locale/cs.js
> +    monthsStrictRegex: /^(leden|ledna|února|únor|březen|března|duben|dubna|květen|května|červenec|července|červen|června|srpena|srpna|srpen|září|říjena|říjen|října|listopada|listopadu|listopad|prosin
Can you also revert this line pls?

2020-10-22 03:43 UTC, Kartik18g commented
@petrbela as you said I've reverted "monthsStrictRegex" to its original value.

2020-10-22 12:15 UTC, petrbela approved these changes

2020-10-23 19:20 UTC, merged

2022-11-04 16:47 UTC, indexxd commented
@marwahaha the inflections here are wrong, i have created a [PR](https://github.com/moment/moment/pull/6063) to fix this 

@petrbela could you please take a look at this?