add Pashto locale
moment/moment pull request #6000
Opened 2022-04-24 06:25 UTC by hanifhefaz

This pull request will add Pashto language locale to moment.js, which is spoken by around 30 millions people in Afghanistan

2026-08-20 21:18 UTC, mattjohnsonpint requested changes
Thanks for contributing this locale! I used AI-assisted research to review the language and locale conventions. I am not a native speaker of Pashto, so I checked the proposed behavior against CLDR and independent sources.

Recommendation: Needs Work

**Findings**
1. **Blocking: the module does not register `ps` and instead overwrites Persian.** `src/locale/ps.js:39` calls `defineLocale('fa', ...)`, then `src/locale/ps.js:122` returns an undefined `ps`. The file also contains a generated UMD wrapper instead of the ES module structure required under `src/locale/`. It should import `moment` from `../moment` and export `moment.defineLocale('ps', ...)`.

2. **Blocking: much of the locale conflicts with current CLDR data.** Examples include several month spellings at `src/locale/ps.js:40`, the year-last `DD/MM/YYYY` date at line 60 instead of CLDR's year-first `y/M/d`, and relative-time forms at lines 84-99 that cannot express CLDR's context-dependent forms. For example, CLDR distinguishes future `په {0} ساعتو کې` from past `{0} ساعتونه مخکې`, while the implementation uses `%d ساعتونه` for both and omits `کې` from the future wrapper. These values need to be reconciled field by field against CLDR or supported with stronger independent evidence.

3. **Blocking: the submitted tests contradict the implementation.** The focused test reports 13 failed tests and 292 failed assertions. Examples include `%d ساعتونه` in the source versus `ساعته` at `src/test/locale/ps.js:193`, `%d کلونه` versus `کاله` at line 283, and future `'په %s'` versus expectations ending in `کي` at lines 312 and 327. There are also internal inconsistencies such as `مخکي` versus `مخکی` at lines 398-410. The corrected implementation and expectations must agree, with tests covering parsing, formatting, contextual relative-time forms, and week boundaries.

4. **Blocking scope issue: `package-lock.json` must be removed.** Locale PRs may only change `src/locale/` and `src/test/locale/`. The lockfile also conflicts because current `develop` has deleted it.

5. **Repository hygiene needs correction.** ESLint reports five errors in `src/locale/ps.js`, including undefined `define` and `ps`, unused `fa`, and the `one-var` violation. Prettier also rejects this file.

**Evidence**
- `ps` is a valid, canonical BCP 47 language tag. The [IANA registry](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry) registers `ps` for Pashto/Pushto with Arabic as its suppress-script. [ISO 639-3](https://iso639-3.sil.org/code/pus) maps `pus` to ISO 639-1 `ps`.
- CLDR expands `ps` to `ps-Arab-AF` in its [likely-subtag data](https://github.com/unicode-org/cldr/blob/95f50133dc17b9d3e4cd355dbe4e30a1ccb1a185/common/supplemental/likelySubtags.xml).
- The relevant current CLDR baseline is [`ps.xml` at commit `95f50133`](https://github.com/unicode-org/cldr/blob/95f50133dc17b9d3e4cd355dbe4e30a1ccb1a185/common/main/ps.xml). It supports the submitted extended Arabic digits and distinguishes Pashto date names and relative-time grammar from Persian, but disagrees with multiple submitted spellings and patterns.
- CLDR's [week data](https://github.com/unicode-org/cldr/blob/95f50133dc17b9d3e4cd355dbe4e30a1ccb1a185/common/supplemental/supplementalData.xml) gives Afghanistan Saturday as the first day and one minimum day in week one. Therefore `dow: 6, doy: 12` is supported.
- Afghanistan's [2004 Constitution, Article 16](https://www.constituteproject.org/constitution/Afghanistan_2004?lang=en) identifies Pashto and Dari as separate official languages.
- [Encyclopaedia Iranica](https://www.iranicaonline.org/articles/afghanistan-vi-pasto/) and [Indiana University](https://celt.indiana.edu/portal/Pashto/index.html) identify Pashto as an Eastern Iranian language distinct from the Western Iranian Persian group.
- No existing Moment locale provides equivalent Pashto behavior. Its verified distinctions from `fa` are substantial enough to justify a separate locale.
- Earlier attempts were PRs [#5092](https://github.com/moment/moment/pull/5092), [#5103](https://github.com/moment/moment/pull/5103), [#5105](https://github.com/moment/moment/pull/5105), and [#5196](https://github.com/moment/moment/pull/5196); none merged.

**Verification**
- `pnpm test -- --only=locale/ps`: failed, 13 of 23 tests and 292 of 1,067 assertions failed.
- `pnpm lint -- src/locale/ps.js src/test/locale/ps.js`: failed with five ESLint errors.
- `pnpm format:check`: failed for `src/locale/ps.js`.
- `pnpm validate`: not run because the focused test and lint already fail.
- The PR conflicts with current `develop`; the local rebase required removing the deleted `package-lock.json`.
- The PR needs linting and formatting.
- The CLA is not signed.

2026-08-21 02:03 UTC, hanifhefaz commented
I don't know to thank you or thank the AI for reviewing my PR after 4 years.

I have a better idea:

Close this PR and tell AI to create one, with fixing all the issues it mentioned in my PR.

🔥🔥🔥

2026-08-21 02:31 UTC, mattjohnsonpint commented
Hopefully the AI gave you enough details to make the necessary improvements.  I'm reviving moment maintenance, so presuming you can complete it satisfactorily, I'll ensure it actually gets released.  I'd still like the main contribution to come from a native speaker of the language, so I'm not going to ask the AI to implement the whole thing.  But let me know when you're ready for re-review and we'll see if it can pass the AI test. 😅

2026-08-21 02:37 UTC, hanifhefaz commented
Sure! Thank you very much. I will try my best to fix it ASAP.

Love ❤️

2026-08-24 11:53 UTC, hanifhefaz commented
The branch was rebased onto current `develop` and the requested changes are addressed. the lock file was removed and the `ps` module registration and structure was corrected. Hopefully this is ready for re-review.

2026-09-02 04:25 UTC, mattjohnsonpint requested changes
Looking pretty good! Only one correction in the implementation and the corresponding test, and then it's good to go!

2026-09-02 04:25 UTC, mattjohnsonpint commented on src/locale/ps.js
> +    weekdays: 'یکشنبه_دوشنبه_سه شنبه_چهارشنبه_پنج شنبه_جمعه_اونۍ'.split('_'),
`dddd` currently outputs `اونۍ` ("week") for Saturday, while current Afghan government date headings use `شنبه`. Please use the supported weekday form here.

```suggestion
    weekdays: 'یکشنبه_دوشنبه_سه شنبه_چهارشنبه_پنج شنبه_جمعه_شنبه'.split('_'),
```

2026-09-02 04:25 UTC, mattjohnsonpint commented on src/test/locale/ps.js
> +            'یکشنبه یکشنبه ی_دوشنبه دوشنبه د_سه شنبه سه شنبه س_چهارشنبه چهارشنبه چ_پنج شنبه پنج شنبه پ_جمعه جمعه ج_اونۍ شنبه ش'.split(
Please update the expected full Saturday output to match the corrected locale.

```suggestion
            'یکشنبه یکشنبه ی_دوشنبه دوشنبه د_سه شنبه سه شنبه س_چهارشنبه چهارشنبه چ_پنج شنبه پنج شنبه پ_جمعه جمعه ج_شنبه شنبه ش'.split(
```

2026-09-02 12:39 UTC, hanifhefaz commented
Both suggestions were applied. This PR is ready for merge from our side.

2026-09-02 14:43 UTC, mattjohnsonpint approved these changes
Thanks for your contribution!  Pashto will be included in the upcoming 2.31.0 release! 🎉

2026-09-02 14:43 UTC, merged

2026-09-02 17:05 UTC, hanifhefaz commented
Glad to see that Pashto finally made it to the awesome moment!