fixed uzbek language relative time translation
moment/moment pull request #6094
Opened 2023-01-25 13:13 UTC by Zukhrik

2023-09-25 06:06 UTC, Zukhrik commented
@ichernev

2023-12-16 21:59 UTC, ichernev commented
@Zukhrik first of all, you need to modify files in `src/locale/` folder. Then you need to fix/update tests. Lastly, I'd need a proof (from [CLDR](https://github.com/unicode-org/cldr/blob/release-44-1/common/main/)) that the changes make sense (I'm not a native speaker :)).

2024-08-08 07:02 UTC, anandfresh approved these changes

2026-08-20 19:54 UTC, mattjohnsonpint requested changes
Thanks for contributing this locale update! I used AI-assisted research to review the language and locale conventions. I am not a native speaker of Uzbek, so I checked the proposed behavior against CLDR and independent dictionary evidence.

Recommendation: Needs Work

The correction is valid, but the PR changes generated files only and has no regression tests.

## Findings

1. **Blocking: the correction must be made in the authoritative source files.** The changes at `locale/uz-latn.js:43` and `locale/uz.js:40` are generated release artifacts and will be overwritten. Apply the equivalent changes to `src/locale/uz-latn.js:36` and `src/locale/uz.js:33`, then remove both `locale/` changes from the PR.

2. **Blocking: regression tests are missing.** Update the past-relative-time expectations around `src/test/locale/uz-latn.js:295` and `src/test/locale/uz.js:292`. Include a counted example such as `5 kun oldin` / `5 кун олдин`, because the current implementation produces the contradictory `Bir necha 5 kun oldin`.

The intended `%s oldin` / `%s олдин` correction itself is appropriate. Moment applies `past` as a wrapper around every relative-time unit, so removing `Bir necha` fixes both uncounted seconds and explicitly counted values.

## Evidence

- Current CLDR Uzbek data consistently uses `{0} <unit> oldin`, without `bir necha`: [years](https://github.com/unicode-org/cldr/blob/95f50133dc17b9d3e4cd355dbe4e30a1ccb1a185/common/main/uz.xml#L2437-L2446), [days](https://github.com/unicode-org/cldr/blob/95f50133dc17b9d3e4cd355dbe4e30a1ccb1a185/common/main/uz.xml#L2611-L2620), [hours](https://github.com/unicode-org/cldr/blob/95f50133dc17b9d3e4cd355dbe4e30a1ccb1a185/common/main/uz.xml#L2960-L2969), and [seconds](https://github.com/unicode-org/cldr/blob/95f50133dc17b9d3e4cd355dbe4e30a1ccb1a185/common/main/uz.xml#L3028-L3037).
- The Uzbek explanatory dictionary defines [`oldin`](https://izoh.uz/word/oldin) for prior time and gives “Bundan bir yil oldin.”
- Its [`necha`](https://izoh.uz/word/necha) entry identifies `bir necha` as an indefinite quantity. Prefixing it to an already counted value changes the meaning and produces malformed phrases.

No related prior PR contradicts this correction. PR #6047 was another generated-only Uzbek typo proposal and did not address relative time.

## Verification

- Rebasing onto the latest `develop` completed without conflicts.
- Temporary source-level changes and tests were used only for review and then removed.
- `pnpm test -- --only=locale/uz`: passed.
- `pnpm test -- --only=locale/uz-latn`: passed.
- `pnpm validate`: passed.
- Rebase, lint, and formatting: no further changes required after correcting the PR scope.
- The PR title check is currently failing.
- CLA: not signed.

2026-08-20 20:11 UTC, mattjohnsonpint commented
Hi again.  I took the liberty to apply your valid suggestion myself in #6409.  So there's no need for further work here.

The fix will be included in the next Moment release.  Thank you!

2026-08-20 20:11 UTC, closed without merging