Update fr-ca.js ordinal behavior to match fr.js
moment/moment pull request #6110
Opened 2023-03-28 22:44 UTC by mrleblanc101

We say Samedi 1er avril, but not Dimanche 2e avril.
The correct for should be Dimanche 2 avril.
I guess I'll override the translation myself in my projet to bring back the previous behavior which was the correct one.

This has been fixed in `fr.json` but not in `fr-ca.json`

2023-05-29 08:36 UTC, suyundukov requested changes
The original issue got closed, so I'm not sure if there is a point in this request.

2023-12-16 21:54 UTC, ichernev commented
@mrleblanc101 I need some better proof about this (CLDR maybe). Also you need to change `src/locale/fr.js` and add tests

2023-12-29 03:44 UTC, mrleblanc101 commented
@ichernev Done

2023-12-29 04:00 UTC, mrleblanc101 commented
Here are some issues I found while fixing the test :(

1) The fix in `fr` that this PR copy in `fr-ca` might not even be entirely correct !
In french we say `1er février`, and `2 février` which this PR will fix.
We only use ordinals for the first day of the month, but there is an edge-case that the current moment.js API doesn't cover.
Sometime `Do` format should be `'er' or ''` and something it should be `'er' or 'e'`.
Here is an exemple from the `test.js` file which is incorrect

The current output in `fr` (which would now be the behavior in `fr-ca`):
```
[
    '[le] Do [jour du mois]', 
    'le 14 jour du mois'
],
```
Should be in both `fr` and `fr-ca`:
```
[
    '[le] Do [jour du mois]', 
    'le 14e jour du mois'
],
```

2) This format is not correct, the day should come before the month in french.
But maybe it's intended so the test match between all locales ?

The current output:
```
[
    'dddd, MMMM Do YYYY, h:mm:ss a',
    'dimanche, février 14 2010, 3:25:50 pm',
],
```
What the output should be:
```
[
    'dddd, Do MMMM YYYY, h:mm:ss a',
    'dimanche, 14 février 2010, 3:25:50 pm',
],
```

2026-08-20 19:49 UTC, mattjohnsonpint requested changes
Thanks for contributing this locale update! I used AI-assisted research to review the language and locale conventions. I am not a native speaker of French.

Recommendation: Needs Work

**Findings**

1. `src/locale/fr-ca.js:52` breaks compatibility with existing strict parsing. Before this PR, `moment('2014 01 2e', 'YYYY MM Do', true)` was valid; afterward it is invalid. The regex should accept both the newly formatted cardinal form and the previously accepted ordinal form, for example `/\d{1,2}(er|e|)/`.
2. The parser change has no regression coverage. Please add strict parsing tests for at least `1er`, `2`, and the compatibility form `2e`. The submitted tests only exercise formatting.
3. `locale/fr-ca.js` is generated release output and must be removed from the PR. Locale corrections may only change `src/locale/` and `src/test/locale/`.
4. `src/test/locale/fr-ca.js:67` documents the known limitation of this context-blind workaround: `le 14e jour du mois` becomes the grammatically incorrect `le 14 jour du mois`. This is also acknowledged by the copied TODO and existing `fr` behavior. It is a residual limitation of Moment's locale API, not evidence that ordinal expressions generally omit `e`.

**Evidence**

- [CLDR `fr_CA`](https://github.com/unicode-org/cldr/blob/95f50133dc17b9d3e4cd355dbe4e30a1ccb1a185/common/main/fr_CA.xml#L2363-L2370) uses cardinal `d` in date patterns, including `d MMMM y`.
- [CLDR parent `fr`](https://github.com/unicode-org/cldr/blob/95f50133dc17b9d3e4cd355dbe4e30a1ccb1a185/common/main/fr.xml#L3317-L3326) likewise uses `EEEE d MMMM y` and `d MMMM y`.
- The [Government of Canada's date guidance](https://www.noslangues-ourlanguages.gc.ca/fr/cles-de-la-redaction/date-regles-decriture) explicitly requires `1er décembre` for the first day and uses cardinal forms such as `9 janvier` for other days. This directly supports the intended `1er`/`2` date behavior.
- The [Government of Canada's ordinal guidance](https://www.noslangues-ourlanguages.gc.ca/fr/cles-de-la-redaction/nombres-ordinaux) and the [Académie française](https://www.academie-francaise.fr/abreviations-des-adjectifs-numeraux) require `e` for ordinary ordinal expressions after the first, supporting `14e jour`.
- Issue [#3375](https://github.com/moment/moment/issues/3375) and commit `6409bef4` establish the existing `fr` workaround and its known contextual limitation.

**Verification**

- The PR rebased cleanly onto current `develop`, without conflicts. The remote branch still needs that rebase.
- `pnpm test -- --only=locale/fr-ca`: passed, 1,100 assertions.
- `pnpm validate`: passed, 163,946 assertions.
- Formatting and diff checks passed.
- The generated-files check currently fails because of `locale/fr-ca.js`.
- The CLA is not signed: EasyCLA cannot associate the second commit's email with the contributor's GitHub account.

2026-09-12 19:59 UTC, closed without merging